#!/usr/bin/env python3
"""Reproduce the porous-medium temperature contour from the paper §5.2.

Target figure: reference/AGEFEM-for-Phonon-BTE-Original/results/figs/Porous_4_1_1_Temp_cg.png
generated by the original AGEFEM prototype on mesh index 4 (medium
refinement), Knudsen pair k = 1 (τ_R = τ_N = 0.01, near-diffusion
regime), MESHTYPE = 1 (AGE mesh).

This script demonstrates the AGEFEM headline claim by running the same
physics on two **different** mesh resolutions:

  - **SMBDG** is run on a **dense** straight-sided mesh (`porous_10.msh`,
    ~8.9k triangles). The geometry of each pore is approximated by the
    mesh's polygonal boundary edges; the AGE sidecar is not provided.
  - **AGEDG** is run on a **sparse** AGE mesh (`porous_2.msh`, ~0.7k
    triangles). The same five circular boundaries are described
    analytically through the geometry sidecar, so boundary-adjacent
    elements use exact-arc quadrature even at this coarse resolution.

The point of the comparison is to show that AGEDG, by capturing exact
pore geometry on a sparse mesh, can produce a contour qualitatively
matching what SMBDG only gets on a far denser polygonal mesh.

Boundary conditions match the prototype's BDINF setup for `Porous_4_1_1`
on all four sides:

  - five pores (tags 1, 5, 9, 10, 11) — diffuse reflection
  - left / right walls (tags 3, 7) — specular reflection (vertical)
  - bottom split segments (tags 2, 8) — periodic with ΔT_bc = −1
  - top    split segments (tags 4, 6) — periodic with ΔT_bc = +1

(ΔT_bc is interpreted by the solver as T_self − T_partner; with this
pairing the partner-side energy density is shifted by Cv·ΔT/(4π) at
each inflow, imposing a unit temperature difference across the
periodic axis.)

Output: `examples/porous/porous_contours.png` — a 2-panel comparison of
SMBDG (dense) vs AGEDG (sparse), with the pore boundaries overlaid.
"""

from __future__ import annotations

import math
import subprocess
import sys
from pathlib import Path

import numpy as np

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parent.parent
SOLVER = REPO_ROOT / "build-openmp" / "callaway_mfem"

# Geometry of the five curved boundaries declared by the porous mesh family.
# Matches the prototype's data_struct (hole tags + Circle entries).
CURVES = [
   dict(boundary_id=1,  center=(0.5, -1.0), radius=0.25),  # bottom half-circle
   dict(boundary_id=5,  center=(0.5,  1.0), radius=0.25),  # top half-circle
   dict(boundary_id=9,  center=(-0.5, -0.5), radius=0.25),  # interior pore (large)
   dict(boundary_id=10, center=(-0.5,  0.5), radius=0.1),   # interior pore (small)
   dict(boundary_id=11, center=(0.5,   0.0), radius=0.1),   # interior pore (small)
]

# Paper §5.2 / prototype Knudsen pair k = 1: τ_R = τ_N = 0.01. To
# reproduce the prototype's contour we match its angular quadrature
# (NPOLE = 1, NAZIM = 40); our solver treats polar_angles == 1 as 2D
# circular quadrature (cx = vg cos(phi), cy = vg sin(phi), weight sums
# to 2π) matching the prototype's VelocityMesh. The prototype uses
# POLYDEG = 4 — we use DG order 3 here as a cheaper but still
# high-order discretisation; the contour structure is the same.
TAU_R = 0.01
TAU_N = 0.01
DG_ORDER = 3
POLAR_ANGLES = 1
AZIMUTHAL_ANGLES = 40

# Mesh choices: dense for SMBDG (so the polygonal boundary approximates
# the circles reasonably) and sparse for AGEDG (to demonstrate that AGE
# elements capture the exact geometry without paying for refinement).
SMBDG_MESH = "../porous_6.msh"
AGEDG_MESH = "../porous_2.msh"


def write_sidecar(out_path: Path) -> None:
   lines = ["version: 1", "curves:"]
   for c in CURVES:
      lines += [
         f"  - boundary_id: {c['boundary_id']}",
         f"    type: circular_arc",
         f"    center: [{c['center'][0]}, {c['center'][1]}]",
         f"    radius: {c['radius']}",
         f"    orientation: cw",  # holes: domain outside circle => cw traversal
      ]
   out_path.write_text("\n".join(lines) + "\n")


def write_config(out_path: Path, mesh_rel: str, geom_rel: str | None,
                 prefix: str) -> None:
   geometry_line = f"  geometry: {geom_rel}\n" if geom_rel else ""
   bcs = []
   # Pores (1, 5, 9, 10, 11): diffuse — matches prototype BDINF type 2.
   for tag in (1, 5, 9, 10, 11):
      bcs += [f"  - name: Hole{tag}", f"    physical_id: {tag}",
              f"    type: non_thermalizing",
              f"    temperature: 0.0"]
   # Left/right walls (3, 7): specular vertical — matches BDINF type 4.
   for tag in (3, 7):
      bcs += [f"  - name: Side{tag}", f"    physical_id: {tag}",
              f"    type: symmetry",
              f"    temperature: 0.0"]
   # Top/bottom (2, 4, 6, 8): periodic with ΔT_bc = ±1 (= T_self - T_partner).
   #   Bottom tags 2, 8 -> ΔT_bc = -1 (self colder than partner top).
   #   Top    tags 4, 6 -> ΔT_bc = +1 (self warmer than partner bottom).
   for tag, dT in [(2, -1.0), (8, -1.0),
                   (4, +1.0), (6, +1.0)]:
      bcs += [f"  - name: Side{tag}", f"    physical_id: {tag}",
              f"    type: periodic",
              f"    temperature: {dT}"]
   out_path.write_text(
      "iteration:\n"
      "  tolerance: 5.0e-5\n"
      "  max_steps: 20000\n"
      "\n"
      "gsis:\n"
      "  enabled: false\n"
      "\n"
      "velocity_mesh:\n"
      f"  polar_angles: {POLAR_ANGLES}\n"
      f"  azimuthal_angles: {AZIMUTHAL_ANGLES}\n"
      "\n"
      "dg:\n"
      f"  order: {DG_ORDER}\n"
      "\n"
      "flow:\n"
      "  specific_heat: 1.0\n"
      "  group_velocity: 1.0\n"
      f"  tau_r: {TAU_R}\n"
      f"  tau_n: {TAU_N}\n"
      "  tau_threshold: 1.0\n"
      "\n"
      "age:\n"
      "  curved_face_tensors: precomputed\n"
      "  edge_quadrature_points: 10\n"
      "  area_quadrature_points: 10\n"
      "\n"
      "files:\n"
      f"  mesh: {mesh_rel}\n"
      f"{geometry_line}"
      f"  output_prefix: {prefix}\n"
      "  output_samples: 109\n"
      "\n"
      "boundary_conditions:\n"
      + "\n".join(bcs) + "\n"
   )


def run_solver(config_path: Path) -> None:
   print(f"  running {config_path.name} ...", flush=True)
   result = subprocess.run(
      [str(SOLVER), "--config", str(config_path), "--solve", "--write-output"],
      capture_output=True, text=True, check=False, cwd=config_path.parent,
   )
   if result.returncode != 0:
      print(result.stdout)
      print(result.stderr, file=sys.stderr)
      raise SystemExit(f"Solver failed for {config_path}")
   for line in result.stdout.splitlines():
      stripped = line.strip()
      if any(k in line for k in ("AGE:", "CIS solve:", "mesh summary:",
                                 "integration total area")):
         print(f"    {stripped}")


def load_cells_csv(path: Path):
   with path.open() as f:
      header = f.readline().split()
      nv = int(header[0])
      ne = int(header[1])
      verts = np.array(
         [list(map(float, f.readline().split())) for _ in range(nv)], dtype=float
      )
      tris = np.zeros((ne, 3), dtype=int)
      cells = np.zeros((ne, 3), dtype=float)
      for i in range(ne):
         parts = f.readline().split()
         tris[i] = [int(p) for p in parts[:3]]
         cells[i] = [float(p) for p in parts[3:6]]
   return verts, tris, cells[:, 0], cells[:, 1], cells[:, 2]


def per_vertex_average(tris: np.ndarray, cell_values: np.ndarray, nv: int) -> np.ndarray:
   v = np.zeros(nv)
   cnt = np.zeros(nv)
   for e in range(tris.shape[0]):
      for i in tris[e]:
         v[i] += cell_values[e]
         cnt[i] += 1
   cnt[cnt == 0] = 1.0
   return v / cnt


# Tags whose boundary edges sit on a curved pore boundary. AGE elements
# adjacent to these tags carry an exact-arc edge in the AGE pipeline; we
# render those edges as true arcs in the AGEDG mesh overlay below.
CURVED_BOUNDARY_TAGS = {c["boundary_id"] for c in CURVES}
CURVE_BY_TAG = {c["boundary_id"]: c for c in CURVES}


def parse_msh_curved_edges(msh_path: Path) -> dict:
   """Parse a Gmsh 2.2 mesh and return a map
        frozenset({v0_idx, v1_idx}) -> physical_tag
      for boundary edges whose physical_tag is on a curved pore boundary.
      Vertex indices are 0-based to match MFEM's internal numbering."""
   edges: dict = {}
   in_elements = False
   with msh_path.open() as fh:
      lines = fh.readlines()
   i = 0
   while i < len(lines):
      line = lines[i].strip()
      if line.startswith("$Elements"):
         n = int(lines[i + 1].strip())
         for j in range(n):
            parts = lines[i + 2 + j].split()
            etype = int(parts[1])
            ntags = int(parts[2])
            if etype != 1:   # line element (boundary edge)
               continue
            phys = int(parts[3])
            if phys not in CURVED_BOUNDARY_TAGS:
               continue
            nodes = [int(p) - 1 for p in parts[3 + ntags:3 + ntags + 2]]
            edges[frozenset(nodes)] = phys
         break
      i += 1
   return edges


# Z-order layering. Contours sit at the bottom, then the pore mask
# (white-filled chord polygon or exact circle), then the mesh edges on
# top so the boundary edges remain visible.
ZORDER_MASK = 2.0
ZORDER_MESH = 3.0


def draw_arc(ax, center, radius, va, vb, color, linewidth, alpha=1.0, n=24,
             zorder=ZORDER_MESH):
   """Draw the short arc between physical points va and vb on the circle
      of given centre and radius."""
   cx, cy = center
   theta_a = math.atan2(va[1] - cy, va[0] - cx)
   theta_b = math.atan2(vb[1] - cy, vb[0] - cx)
   delta = theta_b - theta_a
   if delta > math.pi:
      delta -= 2 * math.pi
   if delta < -math.pi:
      delta += 2 * math.pi
   thetas = np.linspace(theta_a, theta_a + delta, n)
   ax.plot(cx + radius * np.cos(thetas),
           cy + radius * np.sin(thetas),
           color=color, linewidth=linewidth, alpha=alpha, zorder=zorder)


def plot_mesh(ax, verts, tris, curved_edges, pore_tag_edges, *,
              color="0.25", linewidth=0.25, alpha=0.7,
              boundary_color="0.0", boundary_linewidth=0.9,
              boundary_alpha=1.0, zorder=ZORDER_MESH):
   """Draw the mesh edges. Interior edges and ordinary boundary edges
      use the thin (color, linewidth, alpha) style. Edges whose
      undirected key appears in pore_tag_edges (boundary edges sitting
      on a curved pore tag) are emphasised with the thicker
      (boundary_color, boundary_linewidth) style — straight chords for
      SMBDG, true arcs for AGEDG (when the same edge key also appears
      in curved_edges).

      Each undirected edge is drawn exactly once."""
   drawn = set()
   for tri in tris:
      for i in range(3):
         va_idx = int(tri[i])
         vb_idx = int(tri[(i + 1) % 3])
         key = frozenset({va_idx, vb_idx})
         if key in drawn:
            continue
         drawn.add(key)
         va = verts[va_idx]
         vb = verts[vb_idx]
         is_pore_edge = key in pore_tag_edges
         use_color = boundary_color if is_pore_edge else color
         use_lw    = boundary_linewidth if is_pore_edge else linewidth
         use_alpha = boundary_alpha if is_pore_edge else alpha
         if key in curved_edges:
            cinfo = CURVE_BY_TAG[curved_edges[key]]
            draw_arc(ax, cinfo["center"], cinfo["radius"], va, vb,
                     color=use_color, linewidth=use_lw, alpha=use_alpha,
                     zorder=zorder)
         else:
            ax.plot([va[0], vb[0]], [va[1], vb[1]],
                    color=use_color, linewidth=use_lw, alpha=use_alpha,
                    zorder=zorder)


def mask_pores_polygonal(ax, verts, curved_edges):
   """Mask pore interiors with the **chord polygon** of each pore. This
      preserves the polygonal SMBDG boundary as the visible interface
      between coloured domain and white pore — so the polygon's corners
      (the chord-edge geometric approximation error) remain visible
      once the mesh layer is drawn on top."""
   tag_to_verts: dict = {}
   for edge_key, tag in curved_edges.items():
      for v in edge_key:
         tag_to_verts.setdefault(tag, set()).add(v)
   for tag, vset in tag_to_verts.items():
      cinfo = CURVE_BY_TAG[tag]
      cx, cy = cinfo["center"]
      ordered = sorted(
         vset,
         key=lambda v: math.atan2(verts[v][1] - cy, verts[v][0] - cx),
      )
      poly_x = [verts[v][0] for v in ordered]
      poly_y = [verts[v][1] for v in ordered]
      ax.fill(poly_x, poly_y, color="white", zorder=ZORDER_MASK)


def mask_pores_circular(ax):
   """Mask pore interiors with the **exact circle** of each pore — the
      AGE arc that bounds an AGE element. The visible boundary is the
      smooth arc with no geometric error."""
   theta = np.linspace(0, 2 * math.pi, 200)
   for c in CURVES:
      cx, cy = c["center"]
      r = c["radius"]
      ax.fill(cx + r * np.cos(theta), cy + r * np.sin(theta),
              color="white", zorder=ZORDER_MASK)


def main() -> None:
   if not SOLVER.is_file():
      raise SystemExit(f"callaway_mfem not found at {SOLVER}. Build first.")
   try:
      import matplotlib.pyplot as plt
      import matplotlib.tri as mtri
   except ImportError as ex:
      raise SystemExit(f"matplotlib required: {ex}")

   output_dir = THIS_DIR / "output"
   output_dir.mkdir(exist_ok=True)

   # Sidecar is shared between runs (only the AGEDG run consumes it).
   sidecar_path = output_dir / "porous.age.yaml"
   write_sidecar(sidecar_path)

   smb_cfg = output_dir / "control_smbdg.yaml"
   write_config(smb_cfg, SMBDG_MESH, None, "smbdg_porous")
   print("=== SMBDG (dense straight-sided mesh) ===")
   run_solver(smb_cfg)
   v_s, t_s, T_s, _, _ = load_cells_csv(output_dir / "smbdg_porous_cells.csv")

   age_cfg = output_dir / "control_agedg.yaml"
   write_config(age_cfg, AGEDG_MESH, sidecar_path.name, "agedg_porous")
   print("\n=== AGEDG (sparse AGE mesh) ===")
   run_solver(age_cfg)
   v_a, t_a, T_a, _, _ = load_cells_csv(output_dir / "agedg_porous_cells.csv")

   # Shared symmetric colour range across the two panels — matches the
   # prototype's contourf(np.linspace(-vmax, vmax, 21)) style.
   amp = max(abs(T_s.min()), abs(T_s.max()), abs(T_a.min()), abs(T_a.max()))
   amp = math.ceil(amp * 10) / 10  # round up to nearest 0.1 for a clean range
   levels = np.linspace(-amp, amp, 21)

   # Identify curved boundary edges per mesh so AGEDG can render the
   # actual AGE arcs (and SMBDG can render its polygonal chords).
   smb_curved = parse_msh_curved_edges(THIS_DIR / "porous_6.msh")
   age_curved = parse_msh_curved_edges(THIS_DIR / "porous_2.msh")

   fig, axes = plt.subplots(1, 2, figsize=(12, 5.5))

   for ax, verts, tris, Tcell, mesh_curved_edges, pore_mask_kind, label in (
      # SMBDG: chord polygon is the actual boundary of the SMBDG domain;
      # show its corners by masking with the polygon, and draw all
      # element edges (including the chord pore boundary) as straight
      # lines.
      (axes[0], v_s, t_s, T_s, smb_curved, "polygon",
       f"SMBDG  /  {len(t_s)} elements (dense straight-sided mesh)"),
      # AGEDG: AGE arc is the actual boundary of each AGE element; mask
      # with the exact circle so the smooth arc is the visible
      # interface, and draw the curved-tag mesh edges as true arcs.
      (axes[1], v_a, t_a, T_a, age_curved, "circle",
       f"AGEDG  /  {len(t_a)} elements (sparse AGE mesh)"),
   ):
      tri = mtri.Triangulation(verts[:, 0], verts[:, 1], tris)
      v_vals = per_vertex_average(tris, Tcell, len(verts))
      im = ax.tricontourf(tri, v_vals, levels=levels, cmap="coolwarm", extend="both")
      ax.tricontour(tri, v_vals, levels=levels,
                    colors="k", linewidths=0.4, alpha=0.55)
      # Mask pore interior. SMBDG uses the chord polygon (so the
      # polygonal approximation's corners are visible); AGEDG uses the
      # exact circle (so the AGE arc is visible).
      if pore_mask_kind == "polygon":
         mask_pores_polygonal(ax, verts, mesh_curved_edges)
      else:
         mask_pores_circular(ax)
      # Draw the mesh on top. SMBDG renders pore-boundary edges as
      # straight chords (curved_edges = {}) so the polygonal
      # approximation is visible; AGEDG renders them as true arcs (the
      # AGE element's curved edge). In both cases we mark those edges
      # as pore-boundary so they're drawn with the thicker emphasis
      # style, making the polygonal-vs-arc distinction obvious.
      plot_mesh(ax, verts, tris,
                {} if pore_mask_kind == "polygon" else mesh_curved_edges,
                mesh_curved_edges,
                color="0.4", linewidth=0.2, alpha=0.5,
                boundary_color="0.0", boundary_linewidth=1.0,
                boundary_alpha=1.0)
      ax.set_aspect("equal")
      ax.set_title(label)
      plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04,
                   ticks=np.linspace(-amp, amp, 5))

   for ax in axes:
      ax.set_xlim(-1, 1)
      ax.set_ylim(-1, 1)
      ax.set_xticks([])
      ax.set_yticks([])

   fig.suptitle(
      f"Porous medium (paper §5.2), τ_R = τ_N = {TAU_R}, DG order {DG_ORDER}, "
      f"periodic ΔT = 1 (top/bottom), specular L/R, diffuse pores",
      y=1.00, fontsize=11)
   plt.tight_layout()
   plot_path = THIS_DIR / "porous_contours.png"
   plt.savefig(plot_path, dpi=160, bbox_inches="tight")
   print(f"\nWrote {plot_path}")


if __name__ == "__main__":
   main()
